
spring:
  data:
    redis:
      host: localhost
      port: 6379
      password:
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/api/cart/**
          filters:
            - TokenRelay=
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
          filters:
            - TokenRelay=
        - id: ui
          uri: http://localhost:3000
          predicates:
            - Path=/ui/**
          filters:
            - StripPrefix=1
        - id: static
          uri: http://localhost:3000
          predicates:
            - Path=/static/**
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/test
        registration:
          keycloak:
            provider: keycloak
            client-id: gateway
            client-secret: ${SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
              - roles

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
logging:
  level:
    org.springframework.cloud.gateway: TRACE

